name: create-artifact
on: 
  workflow_dispatch:
  pull_request:
    types: [closed]
jobs:
  publish_zip_archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/upload-artifact@v1
        with:
          name: automation-function
          path: ${{ github.workspace }}/src/automation

  
