name: Validate PR
on: pull_request
jobs:
  validate_bicep_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: src/infrastructure/mainTemplate.bicep
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#
          INPUT_JSONS: src/infrastructure/mainTemplate.json
      