name: validate-PR
on: [pull_request, workflow_dispatch]
jobs:
  validate_bicep_and_dotnet_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: src/infrastructure/mainTemplate.bicep
      - name: Run ARM TTK
        uses: aliencube/arm-ttk-actions@v0.3
        id: armtest
        with:
          path: src/infrastructure
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - run: dotnet publish src/automation/automation.csproj -o release
      - uses: actions/upload-artifact@v1
        with:
          name: automation-function
          path: ${{ github.workspace }}/release
  
