name: validate-PR
on: pull_request
jobs:
  validate_bicep_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Bicep
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az bicep build ./src/infrastructure/mainTemplate.bicep
      - name: Run ARM TTK
        uses: aliencube/arm-ttk-actions@v0.3
        id: armtest
        with:
          path: src/infrastructure
  
